name: Release

env:
  DEPLOY_HOOK_URL: ${{ secrets.DEPLOY_HOOK_URL }}

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -X POST -d {} ${{ secrets.DEPLOY_HOOK_URL }}
